### ISSUE TITLE
Player in platformer doesn't land on platforms.

### ISSUE THREAD

**Issue by ALEX-DAWSON** [ALEX-DAWSON/DawsonsGames#3]
The ***player*** in the platformer game doesn't land on the platforms. The player is represented by the red square and the platforms are represented by the blue platforms. Everything can be found in  `platformer/platformer.js`. 
Also, I know that my code seems a little *noob-ish*, but this is the first time I've coded in JavaScript, especially with something like this.
### Would greatly appreciate if someone could give me some pointers.

**Comment by tomdaly** [comment]
Hey @ALEX-DAWSON, noticed your 'help wanted' tag and had a look at your projects and you've done a great job so far. I noticed your '*All the tutorials I've seen come from people who understand this way better than I do*' comment and just wanted to let you know that you shouldn't worry about that, getting good at coding comes with practice, so keep at it. The people making tutorial videos always seem far ahead, but it's only because they've written enough code to be good enough to make a video about it :)

Anyway, I had a play with the platformer game and realised what the issue is. In `platformer/script.js`, lines 59-74, your code attempts to find out whether the player is touching the top of the platform. If you think about what that means, you're trying to find out if any side of the player square intersects with a side of the platform, and if so you want to reset the player's position back above the platform so that it appears to 'land' on the platforms. 

With that in mind, you know that if the player's x position (`PlayerX`) is within the start and end of the platform, they are either above or below (or inside) the platform. From that, you get this line of code:
```
if (PlayerX >= x && PlayerX <= x + PlatformWidth)
```
but as you probably already know, in JavaScript the canvas is drawn from the top-left so you need to account for the PlayerSize when dealing with the left side of the platform, so you modify the line to get this:
```
if (PlayerX + PlayerSize <= x && PlayerX <= x + PlatformWidth)
```

Now that you've dealt with the X position, you can think about the Y position. You want to check if the player's Y position (and don't forget about the player's size!) is higher than the platforms top position (y) - you need to check for **greater than** because as mentioned before, JavaScript draws from the top-left to the bottom-right so as the player falls down its Y value is actually increasing. All that thinking modifies the code to look like this:
```
if (PlayerX + PlayerSize <= x && PlayerX <= x + PlatformWidth) && (PlayerY + PlayerSize >= y))
```
If you left it like that, the player would be launched back to the top of the platform if they went under the platform (as the player y position would still be less than the platform y position). To fix that, you want to check if the player y position is less than the y position plus the platform height.
```
if ((PlayerX + PlayerSize >= x && PlayerX <= x + PlatformWidth) && (PlayerY + PlayerSize >= y) && (PlayerY + PlayerSize <= y + PlatformHeight))
```

And finally, as you've made an if statement, you want it to actually do something. Adding this means the player's y position will be reset to the platforms y value (accounting for player size).
```
if ((PlayerX + PlayerSize >= x && PlayerX <= x + PlatformWidth) && (PlayerY + PlayerSize >= y) && (PlayerY + PlayerSize <= y + PlatformHeight)) {
    console.log("player hit platform floor");
    PlayerY = y - PlayerSize;
}
```

And that's it. Replace lines 59-74 with these lines and see if it works for you. Hopefully that made sense, I was going to just comment the last solution but thought it would benefit you more if it was fully explained (as sometimes the tutorial videos don't explain it well either). With this logic, try thinking about creating a new if statement to check if the player has hit the platforms ceiling.
